export const f1Tracks = [
  "Bahrain International Circuit",
  "Jeddah Corniche Circuit",
  "Albert Park (Melbourne)",
  "Suzuka Circuit",
  "Shanghai International Circuit",
  "Miami International Autodrome",
  "Imola (Autodromo Enzo e Dino Ferrari)",
  "Circuit de Monaco",
  "Circuit de Barcelona-Catalunya",
  "Red Bull Ring",
  "Silverstone Circuit",
  "Hungaroring",
  "Circuit de Spa-Francorchamps",
  "Zandvoort",
  "Monza (Autodromo Nazionale di Monza)",
  "Baku City Circuit",
  "Marina Bay Street Circuit",
  "Circuit of the Americas",
  "Autodromo Hermanos Rodriguez",
  "Interlagos (Autodromo Jose Carlos Pace)",
  "Las Vegas Strip Circuit",
  "Lusail International Circuit",
  "Yas Marina Circuit",
];
